# Generated by Django 4.1.7 on 2023-02-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.IntegerField(choices=[(1, 'О Проектк'), (2, 'Направление'), (3, 'Задачи'), (4, 'Результаты'), (5, 'Контакты'), (6, 'Регистрация')], default=1),
        ),
    ]
